[package]
name = "candle-kernels"
version = "0.9.2-alpha.2"
edition = "2021"

description = "CUDA kernels for Candle"
repository = "https://github.com/huggingface/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]

[build-dependencies]
bindgen_cuda = { git = "https://github.com/Narsil/bindgen_cuda.git" }
