[package]
name = "candle-wasm-example"
version = "0.1.0"
edition = "2021"

description = "Wasm example for the candle ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle = { path = "../candle-core" }
candle-nn = { path = "../candle-nn" }
wasm-bindgen = "0.2.87"
getrandom = { version = "0.2", features = ["js"] }
tokenizers = { version = "0.13.3", default-features=false, features=["unstable_wasm"] }
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
wav = "1.0.0"
rand = "0.8.5"
num-traits = "0.2.15"
anyhow = "1.0.71"
js-sys = "0.3.64"
wasm-bindgen-futures = "0.4.37"

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Blob',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Request',
  'RequestCache',
  'RequestInit',
  'RequestMode',
  'Response',
]
