[package]
name = "candle-wasm-example"
version = "0.1.0"
edition = "2021"

description = "Wasm example for the candle ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle = { path = "../candle-core", default-features=false }
candle-nn = { path = "../candle-nn", default-features=false }
num-traits = "0.2.15"
tokenizers = { version = "0.13.3", default-features=false, features=["unstable_wasm"] }

# App crates.
anyhow = "1.0.71"
log = "0.4"
rand = "0.8.5"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
wav = "1.0.0"

# Wasm specific crates.
getrandom = { version = "0.2", features = ["js"] }
gloo = "0.8"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wasm-logger = "0.2"
yew = { version = "0.20.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Blob',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Request',
  'RequestCache',
  'RequestInit',
  'RequestMode',
  'Response',
]
