[package]
name = "candle-flash-attn-build"
version = "0.9.2"
edition = "2021"

description = "Build utilities for candle flash attention crates"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
