repos:
  - repo: https://github.com/Narsil/pre-commit-rust
    rev: 2eed6366172ef2a5186e8785ec0e67243d7d73d0
    hooks:
      - id: fmt
        name: "Rust (fmt)"
      - id: clippy
        name: "Rust (clippy)"
        args:
          [
            "--tests",
            "--examples",
            "--",
            "-Dwarnings",
          ]
