[package]
name = "candle-wasm-example-quant-embed-gemma"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []

[dependencies]
candle = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true} 
tokenizers = { workspace = true, features = ["unstable_wasm"] }
num-traits = { workspace = true }
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
tracing = "0.1"

# App crates.
anyhow = { workspace = true }
byteorder = { workspace = true }
getrandom = { version = "0.3", features = ["wasm_js"], default-features = false }
image = { workspace = true }
log = { workspace = true }
safetensors = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rayon = { workspace = true }
libc = "0.2"


# Wasm specific crates.
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
web-sys = { version = "0.3.70", features = ["console", "Window", "Performance"] }

