[package]
name = "candle-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
accelerate-src = { workspace = true, optional = true }
byteorder = { workspace = true }
candle-kernels = { workspace = true, optional = true }
candle-metal-kernels = { workspace = true, optional = true }
candle-wgpu-kernels = { workspace = true, optional = true }
metal = { workspace = true, optional = true}
cudarc = { workspace = true, optional = true }
gemm = { workspace = true }
half = { workspace = true }
intel-mkl-src = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
memmap2 = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
rayon = { workspace = true }
safetensors = { workspace = true }
thiserror = { workspace = true }
yoke = { workspace = true }
zip = { workspace = true }
tracing = {workspace = true}
tracing-subscriber = "0.3.18"
tracing-chrome={workspace = true}


#Wgpu Dependencies:
wgpu = { workspace = true, optional = true}
flume = { workspace = true, optional = true}
bytemuck = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tracing-mutex = {workspace = true} #only for debug purposes
log = {workspace = true}

#only for debugging on wasm
#wasm-bindgen = "0.2.87"
#wasm-bindgen-futures = "0.4.37"
#wasm-logger = "0.2"

[dev-dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
#criterion = { workspace = true, features = ["html_reports"]}
criterion = {version= "0.5.1", features = ["html_reports"]}

[build-dependencies]
fancy-regex = "0.13.0"

[features]
cuda = ["cudarc", "dep:candle-kernels"]
cudnn = ["cuda", "cudarc/cudnn"]
mkl = ["dep:libc", "dep:intel-mkl-src"]
accelerate = ["dep:libc", "dep:accelerate-src"]
metal = ["dep:metal", "dep:candle-metal-kernels"]
wgpu = ["dep:wgpu", "dep:pollster", "dep:bytemuck", "dep:flume", "dep:candle-wgpu-kernels"]
wgpu_debug = ["wgpu", "dep:serde", "dep:serde_json"]
#default = ["wgpu_debug"]
default = ["wgpu"]

[[bench]]
name = "bench_main"
harness = false