[package]
name = "candle-pyo3"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[lib]
name = "candle"
crate-type = ["cdylib"]

[dependencies]
candle = { path = "../candle-core", version = "0.2.3", package = "candle-core" }
candle-nn = { path = "../candle-nn", version = "0.2.3" }
half = { workspace = true }
pyo3 = { version = "0.19.0", features = ["extension-module"] }

[build-dependencies]
pyo3-build-config = "0.19"

[features]
default = []
cuda = ["candle/cuda"]
