[package]
name = "candle-pyo3"
version = "0.1.0"
edition = "2021"

description = "PyO3 bindings for the candle ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "candle"
crate-type = ["cdylib"]
doc = false

[dependencies]
candle = { workspace = true }
pyo3 = { version = "0.19.0", features = ["extension-module"] }
half = { workspace = true }

[features]
default = []
cuda = ["candle/cuda"]
