[package]
name = "candle-wgpu-kernels"
version.workspace = true
edition.workspace = true
description = "Wgpu kernels for Candle"
repository = "https://github.com/huggingface/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
wgpu-compute-engine-pwgsl = {path = "../wgpu-compute-engine/wgpu-compute-engine-pwgsl"}
wgpu-compute-engine = { path = "../wgpu-compute-engine" }

[build-dependencies]
wgpu-compute-engine-pwgsl = {path = "../wgpu-compute-engine/wgpu-compute-engine-pwgsl"}

[features]
wgpu_debug_serialize = ["dep:serde", "dep:serde_json"]
default=[]

