[package]
name = "candle-wgpu-kernels"
version = "0.9.2-alpha.1"
edition = "2021"

description = "Wgpu kernels for Candle"
repository = "https://github.com/huggingface/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
candle-wgpu-kernels-macro = {path = "./candle-wgpu-kernels-macro"}
candle-pwgsl = {path = "./candle-pwgsl"}

[build-dependencies]
candle-pwgsl = {path = "./candle-pwgsl"}

[features]
wgpu_debug_serialize = ["dep:serde", "dep:serde_json"]
default=[]

