name: CI / cuda

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-cuda:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on:
      group: aws-g4dn-2xlarge
    container:
      image: nvidia/cuda:13.0.2-cudnn-devel-ubuntu24.04
    if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      security-events: write
    env:
      CUDA_COMPUTE_CAP: 86
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: apt-get update && apt install curl build-essential libssl-dev protobuf-compiler pkg-config -y
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test (cuda)
        run: cargo test --features cuda
